---

- name: Install MySQL
  apt:
    name={{ item }}
    state=present
  with_items:
    - mysql-server
    - python-mysqldb
  notify: start mysql
  tags: install

- name: Copy mysql.cnf to fix Craft issues with MYSQL 5.7+
  template:
    src=my.cnf.j2
    dest=/etc/mysql/my.cnf
    owner=root
    group=root mode=0600
  tags: install

- name: Set up a cron to keep mysql optimised
  cron:
    name="mysqlcheck optimise"
    minute="33"
    hour="4"
    job="mysqlcheck -o --all-databases > /dev/null 2>&1"
  tags: install
