---

- include_vars: "defaults/main.yml"

- name: update mysql root password
  mysql_user:
    name=root
    password="{{ ansible_role_mysql.password }}"
    host="{{ item }}"
    login_user=root
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: copy user my.cnf file with root passwd credentials
  template:
    src=.my.cnf.j2
    dest=/root/.my.cnf
    owner=root
    group=root mode=0600

- name: delete anonymous mysql user
  mysql_user:
    name=""
    state=absent
    login_user=root
    login_password="{{ ansible_role_mysql.password }}"

- name: remove mysql test database
  mysql_db:
    name=test
    state=absent
    login_user=root
    login_password="{{ ansible_role_mysql.password }}"
